[en]
  languageName = "English"
  languageCode = "en-US"
  weight = 10
  [en.params]
    languageISO = "EN"

[pt]
  languageName = "Portuguese"
  languageCode = "pt-PT"
  weight = 20
  [pt.params]
    languageISO = "PT"

[es]
  languageName = "Español"
  languageCode = "es-EC"
  weight = 10
  [es.params]
    languageISO = "ES"
