# Site Params

# Open Graph, Twitter Cards and schema.org Thing and Article (in posts)
# https://gohugo.io/templates/internal/#open-graph
# https://gohugo.io/templates/internal/#twitter-cards
# https://schema.org/Thing
# https://schema.org/Article
description = "Aquí se construye el futuro de Mejía."
images = ['images/logo.svg','images/site-feature-image.png']
mainMenuLogo = "images/logo.svg"

# For favicons
## Chrome Browser
themeColor = "#fff"

# Alert
alert = false
alertDismissable = true
alertText = "Introducing this new service! <a class=\"alert-link stretched-link\" href=\"https://salvus.site/\">Check out Total Security</a>"

# Pre-footer
footerAbout = true
footerAboutTitle = "Few Words About Us"
footerAboutText = "We protect your website so you can provide a safe environment to build trust and improve the user experience of your visitors.<br/><br/>Salvus Site is the partner that you can rely on for preventive and reactive cybersecurity."

# Physical Address Details
address_street = "Calle Cristóbal Colón S3-107"
address_province = "Provincia de Pichincha, 171111"
address_country = "Ecuador"

# OpenStreetMap Coordinates for the map
enableOSM = true
latitude = "-0.5159352810421839" # Approximate coordinates for Machachi
longitude = "-78.56452879917067"
mapZoom = 17

# Text for the popup marker on the map (HTML is allowed)
mapMarkerText = "<b>Sede del Movimiento Fénix</b><br>Machachi, Ecuador."

# Custom Map Marker Settings
enableCustomMarker = true
customMarkerPath = "/images/marker-fenix-bk-v2.png" # Path within the assets folder
customMarkerSize = [32, 48] # [width, height] in pixels
customMarkerAnchor = [16, 48] # The point of the icon that corresponds to the map location (usually bottom-center)
customMarkerPopupAnchor = [0, -48] # The point from which the popup should open, relative to the anchor

[contactForm]
  title = "Formulario de Contacto"
  intro = "¿Tiene alguna pregunta, sugerencia o desea unirse a nuestro movimiento? Envíenos un mensaje y nos pondremos en contacto con usted."
  nameLabel = "Su Nombre"
  namePlaceholder = "Nombre Apellido"
  emailLabel = "Su Correo Electrónico"
  emailPlaceholder = "nombre@ejemplo.com"
  messageLabel = "Mensaje"
  messagePlaceholder = "Escriba su mensaje aquí..."
  buttonText = "Enviar Mensaje"

[options]
  bootStrapJs = true
  breadCrumb = false
  listCategoryFilter = true
  listTagFilter = true
