[[main]]
name = "Home"
url = ""
weight = 10

[[main]]
name = "About"
url = "about"
weight = 20
title = "Made with ❤️ by the Hugo Bootstrap Theme team"

[[main]]
identifier = "blog"
name = "Blog"
weight = 40

[[main]]
name = "All"
url = "post"
weight = 100
parent = "blog"

[[main]]
name = "Hugo"
url = "tags/hugo"
weight = 20
parent = "blog"

[[main]]
name = "Bootstrap"
url = "tags/bootstrap"
weight = 30
parent = "blog"

[[main]]
identifier = "docs"
name = "Docs"
url = "page"
weight = 50

[[social]]
  name = "Facebook"
  pre = "<svg class='bi bi-facebook'><use href='/icons/bootstrap-icons.svg#facebook'/></svg>"
  url = "https://facebook.com/your-page-name/"
  weight = 10
  title = "Follow us on Facebook"

[[social]]
  name = "TikTok"
  pre = "<svg class='bi bi-tiktok'><use href='/icons/bootstrap-icons.svg#tiktok'/></svg>"
  url = "https://www.tiktok.com/@your-username/"
  weight = 20
  title = "Follow us on TikTok"
