# [[main]]
# name = "Sobre Nosotros"
# url = "sobre-nosotros"
# weight = 10
#
# # [[main]]
# # identifier = "actualidad"
# # name = "Actualidad"
# # url = "actualidad"
# # weight = 20
#
# [[main]]
# name = "Transparencia"
# url = "transparencia"
# weight = 30
#
# [[social]]
#   name = "Facebook"
#   pre = "<svg xmlns='http://www.w3.org/2000/svg' class='bi bi-facebook'><use href='/icons/bootstrap-icons.svg#facebook'/></svg>"
#   url = "https://www.facebook.com/M.A.C.FE.LISTA110"
#   weight = 10
#   title = "Síquenos en Facebook."
#
# [[social]]
#   name = "TikTok"
#   pre = "<svg class='bi bi-tiktok'><use href='/icons/bootstrap-icons.svg#tiktok'/></svg>"
#   url = "https://www.tiktok.com/@movimientofenix110"
#   weight = 20
#   title = "Síguenos en Tiktok."
